// Code generated by protoc-gen-micro. DO NOT EDIT.
// versions:
// protoc-gen-go v3.10.0
// source: proto/alert/alert.proto

package alert

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/ycxwi/micro/v3/service/api"
	client "github.com/ycxwi/micro/v3/service/client"
	server "github.com/ycxwi/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Alert service

func NewAlertEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Alert service

type AlertService interface {
	// ReportEvent does event ingestions.
	ReportEvent(ctx context.Context, in *ReportEventRequest, opts ...client.CallOption) (*ReportEventResponse, error)
}

type alertService struct {
	c    client.Client
	name string
}

func NewAlertService(name string, c client.Client) AlertService {
	return &alertService{
		c:    c,
		name: name,
	}
}

func (c *alertService) ReportEvent(ctx context.Context, in *ReportEventRequest, opts ...client.CallOption) (*ReportEventResponse, error) {
	req := c.c.NewRequest(c.name, "Alert.ReportEvent", in)
	out := new(ReportEventResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Alert service

type AlertHandler interface {
	// ReportEvent does event ingestions.
	ReportEvent(context.Context, *ReportEventRequest, *ReportEventResponse) error
}

func RegisterAlertHandler(s server.Server, hdlr AlertHandler, opts ...server.HandlerOption) error {
	type alert interface {
		ReportEvent(ctx context.Context, in *ReportEventRequest, out *ReportEventResponse) error
	}
	type Alert struct {
		alert
	}
	h := &alertHandler{hdlr}
	return s.Handle(s.NewHandler(&Alert{h}, opts...))
}

type alertHandler struct {
	AlertHandler
}

func (h *alertHandler) ReportEvent(ctx context.Context, in *ReportEventRequest, out *ReportEventResponse) error {
	return h.AlertHandler.ReportEvent(ctx, in, out)
}
