// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: proto/api/api.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ApiClient is the client API for Api service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApiClient interface {
	AddToBlockList(ctx context.Context, in *AddToBlockListRequest, opts ...grpc.CallOption) (*AddToBlockListResponse, error)
	RemoveFromBlockList(ctx context.Context, in *RemoveFromBlockListRequest, opts ...grpc.CallOption) (*RemoveFromBlockListResponse, error)
	ReadBlockList(ctx context.Context, in *ReadBlockListRequest, opts ...grpc.CallOption) (*ReadBlockListResponse, error)
}

type apiClient struct {
	cc grpc.ClientConnInterface
}

func NewApiClient(cc grpc.ClientConnInterface) ApiClient {
	return &apiClient{cc}
}

func (c *apiClient) AddToBlockList(ctx context.Context, in *AddToBlockListRequest, opts ...grpc.CallOption) (*AddToBlockListResponse, error) {
	out := new(AddToBlockListResponse)
	err := c.cc.Invoke(ctx, "/api.Api/AddToBlockList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) RemoveFromBlockList(ctx context.Context, in *RemoveFromBlockListRequest, opts ...grpc.CallOption) (*RemoveFromBlockListResponse, error) {
	out := new(RemoveFromBlockListResponse)
	err := c.cc.Invoke(ctx, "/api.Api/RemoveFromBlockList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) ReadBlockList(ctx context.Context, in *ReadBlockListRequest, opts ...grpc.CallOption) (*ReadBlockListResponse, error) {
	out := new(ReadBlockListResponse)
	err := c.cc.Invoke(ctx, "/api.Api/ReadBlockList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiServer is the server API for Api service.
// All implementations must embed UnimplementedApiServer
// for forward compatibility
type ApiServer interface {
	AddToBlockList(context.Context, *AddToBlockListRequest) (*AddToBlockListResponse, error)
	RemoveFromBlockList(context.Context, *RemoveFromBlockListRequest) (*RemoveFromBlockListResponse, error)
	ReadBlockList(context.Context, *ReadBlockListRequest) (*ReadBlockListResponse, error)
	mustEmbedUnimplementedApiServer()
}

// UnimplementedApiServer must be embedded to have forward compatible implementations.
type UnimplementedApiServer struct {
}

func (UnimplementedApiServer) AddToBlockList(context.Context, *AddToBlockListRequest) (*AddToBlockListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddToBlockList not implemented")
}
func (UnimplementedApiServer) RemoveFromBlockList(context.Context, *RemoveFromBlockListRequest) (*RemoveFromBlockListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveFromBlockList not implemented")
}
func (UnimplementedApiServer) ReadBlockList(context.Context, *ReadBlockListRequest) (*ReadBlockListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadBlockList not implemented")
}
func (UnimplementedApiServer) mustEmbedUnimplementedApiServer() {}

// UnsafeApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApiServer will
// result in compilation errors.
type UnsafeApiServer interface {
	mustEmbedUnimplementedApiServer()
}

func RegisterApiServer(s grpc.ServiceRegistrar, srv ApiServer) {
	s.RegisterService(&Api_ServiceDesc, srv)
}

func _Api_AddToBlockList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddToBlockListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).AddToBlockList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/AddToBlockList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).AddToBlockList(ctx, req.(*AddToBlockListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_RemoveFromBlockList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFromBlockListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).RemoveFromBlockList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/RemoveFromBlockList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).RemoveFromBlockList(ctx, req.(*RemoveFromBlockListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_ReadBlockList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadBlockListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).ReadBlockList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/ReadBlockList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).ReadBlockList(ctx, req.(*ReadBlockListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Api_ServiceDesc is the grpc.ServiceDesc for Api service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Api_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.Api",
	HandlerType: (*ApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddToBlockList",
			Handler:    _Api_AddToBlockList_Handler,
		},
		{
			MethodName: "RemoveFromBlockList",
			Handler:    _Api_RemoveFromBlockList_Handler,
		},
		{
			MethodName: "ReadBlockList",
			Handler:    _Api_ReadBlockList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/api/api.proto",
}
