// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: github.com/ycxwi/micro/v3/service/network/mucp/proto/network.proto

package go_micro_network_mucp

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
