// Code generated by protoc-gen-micro. DO NOT EDIT.
// versions:
// protoc-gen-go v3.10.0
// source: proto/errors/errors.proto

package errors

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
